# Generated by Django 4.2.6 on 2024-02-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateField(default='2000-08-04'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=52),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(default='', max_length=52),
        ),
    ]
